name: Publish Kata 2.x release artifacts
on:
  push:
    tags:
     - '2.*'

jobs:
  get-artifact-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get the list
        run: |
         pushd $GITHUB_WORKSPACE
         tag=$(echo $GITHUB_REF | cut -d/ -f3-)
         git checkout $tag
         popd
         $GITHUB_WORKSPACE/tools/packaging/artifact-list.sh > artifact-list.txt
      - name: save-artifact-list
        uses: actions/upload-artifact@v2
        with:
          name: artifact-list
          path: artifact-list.txt

  build-kernel:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    env:
      buildstr: "install_kernel"
    steps:
      - uses: actions/checkout@v2
      - name: get-artifact-list
        uses: actions/download-artifact@v2
        with:
          name: artifact-list
      - run: |
         sudo apt-get update && sudo apt install -y flex bison libelf-dev bc iptables
      - name: build-kernel
        run: |
         if grep -q $buildstr artifact-list.txt; then
           $GITHUB_WORKSPACE/.github/workflows/generate-local-artifact-tarball.sh $buildstr
           echo "artifact-built=true" >> $GITHUB_ENV
         else
           echo "artifact-built=false" >> $GITHUB_ENV
         fi
      - name: store-artifacts
        if: ${{ env.artifact-built }} == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: kata-artifacts
          path: kata-static-kernel.tar.gz

  build-experimental-kernel:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    env:
      buildstr: "install_experimental_kernel"
    steps:
      - uses: actions/checkout@v2
      - name: get-artifact-list
        uses: actions/download-artifact@v2
        with:
          name: artifact-list
      - run: |
         sudo apt-get update && sudo apt install -y flex bison libelf-dev bc iptables
      - name: build-experimental-kernel
        run: |
         if grep -q $buildstr artifact-list.txt; then
           $GITHUB_WORKSPACE/.github/workflows/generate-local-artifact-tarball.sh $buildstr
           echo "artifact-built=true" >> $GITHUB_ENV
         else
           echo "artifact-built=false" >> $GITHUB_ENV
         fi
      - name: store-artifacts
        if: ${{ env.artifact-built }} == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: kata-artifacts
          path: kata-static-experimental-kernel.tar.gz

  build-qemu:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    env:
      buildstr: "install_qemu"
    steps:
      - uses: actions/checkout@v2
      - name: get-artifact-list
        uses: actions/download-artifact@v2
        with:
          name: artifact-list
      - name: build-qemu
        run: |
         if grep -q $buildstr artifact-list.txt; then
           $GITHUB_WORKSPACE/.github/workflows/generate-local-artifact-tarball.sh $buildstr
           echo "artifact-built=true" >> $GITHUB_ENV
         else
           echo "artifact-built=false" >> $GITHUB_ENV
         fi
      - name: store-artifacts
        if: ${{ env.artifact-built }} == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: kata-artifacts
          path: kata-static-qemu.tar.gz

  build-image:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    env:
      buildstr: "install_image"
    steps:
      - uses: actions/checkout@v2
      - name: get-artifact-list
        uses: actions/download-artifact@v2
        with:
          name: artifact-list
      - name: build-image
        run: |
         if grep -q $buildstr artifact-list.txt; then
           $GITHUB_WORKSPACE/.github/workflows/generate-local-artifact-tarball.sh $buildstr
           echo "artifact-built=true" >> $GITHUB_ENV
         else
           echo "artifact-built=false" >> $GITHUB_ENV
         fi
      - name: store-artifacts
        if: ${{ env.artifact-built }} == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: kata-artifacts
          path: kata-static-image.tar.gz

  build-firecracker:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    env:
      buildstr: "install_firecracker"
    steps:
      - uses: actions/checkout@v2
      - name: get-artifact-list
        uses: actions/download-artifact@v2
        with:
          name: artifact-list
      - name: build-firecracker
        run: |
         if grep -q $buildstr artifact-list.txt; then
           $GITHUB_WORKSPACE/.github/workflows/generate-local-artifact-tarball.sh $buildstr
           echo "artifact-built=true" >> $GITHUB_ENV
         else
           echo "artifact-built=false" >> $GITHUB_ENV
         fi
      - name: store-artifacts
        if: ${{ env.artifact-built }} == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: kata-artifacts
          path: kata-static-firecracker.tar.gz


  build-clh:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    env:
      buildstr: "install_clh"
    steps:
      - uses: actions/checkout@v2
      - name: get-artifact-list
        uses: actions/download-artifact@v2
        with:
          name: artifact-list
      - name: build-clh
        run: |
         if grep -q $buildstr artifact-list.txt; then
           $GITHUB_WORKSPACE/.github/workflows/generate-local-artifact-tarball.sh $buildstr
           echo "artifact-built=true" >> $GITHUB_ENV
         else
           echo "artifact-built=false" >> $GITHUB_ENV
         fi
      - name: store-artifacts
        if: ${{ env.artifact-built }} == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: kata-artifacts
          path: kata-static-clh.tar.gz

  build-kata-components:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    env:
      buildstr: "install_kata_components"
    steps:
      - uses: actions/checkout@v2
      - name: get-artifact-list
        uses: actions/download-artifact@v2
        with:
          name: artifact-list
      - name: build-kata-components
        run: |
         if grep -q $buildstr artifact-list.txt; then
           $GITHUB_WORKSPACE/.github/workflows/generate-local-artifact-tarball.sh $buildstr
           echo "artifact-built=true" >> $GITHUB_ENV
         else
           echo "artifact-built=false" >> $GITHUB_ENV
         fi
      - name: store-artifacts
        if: ${{ env.artifact-built }} == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: kata-artifacts
          path: kata-static-kata-components.tar.gz

  gather-artifacts:
    runs-on: ubuntu-16.04
    needs: [build-experimental-kernel, build-kernel, build-qemu, build-image, build-firecracker, build-kata-components, build-clh]
    steps:
      - uses: actions/checkout@v2
      - name: get-artifacts
        uses: actions/download-artifact@v2
        with:
          name: kata-artifacts
          path: kata-artifacts
      - name: colate-artifacts
        run: |
          $GITHUB_WORKSPACE/.github/workflows/gather-artifacts.sh
      - name: store-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-candidate
          path: kata-static.tar.xz

  upload-static-tarball:
    needs: gather-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download-artifacts
        uses: actions/download-artifact@v2
        with:
          name: release-candidate
      - name: install hub
        run: |
          HUB_VER=$(curl -s "https://api.github.com/repos/github/hub/releases/latest" | jq -r .tag_name | sed 's/^v//')
          wget -q -O- https://github.com/github/hub/releases/download/v$HUB_VER/hub-linux-amd64-$HUB_VER.tgz | \
          tar xz --strip-components=2 --wildcards '*/bin/hub' && sudo mv hub /usr/local/bin/hub
      - name: push static tarball to github
        run: |
          tag=$(echo $GITHUB_REF | cut -d/ -f3-)
          tarball="kata-static-$tag-x86_64.tar.xz"
          mv kata-static.tar.xz "$GITHUB_WORKSPACE/${tarball}"
          pushd $GITHUB_WORKSPACE
          echo "uploading asset '${tarball}' for tag: ${tag}"
          GITHUB_TOKEN=${{ secrets.GIT_UPLOAD_TOKEN }} hub release edit -m "" -a "${tarball}" "${tag}"
